import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  header: {
    marginTop: 70,
    marginBottom: 10,
    paddingHorizontal: 20,
  },
  sectionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: '#424242',
  },
  sectionButtonText: {
    color: '#424242',
    fontSize: 16,
    fontFamily: 'Poppins_500Medium',
  },
  activeSectionButton: {
    backgroundColor: '#424242',
    color: '#f9f9f9',
  },
  title: {
    fontSize: 22,
    color: '#424242',
    fontFamily: 'Poppins_700Bold',
  },
  userName: {
    fontSize: 18,
    color: '#dba826ff',
    marginBottom: -5,
    fontFamily: 'Poppins_600SemiBold',
  },
  appName: {
    fontSize: 13,
    color: '#666',
    fontFamily: 'Poppins_500Medium',
  },
  shortcutsContainer: {
    marginBottom: 30,
    paddingHorizontal: 20,
  },
  shortcutsColumn: {
    flexDirection: 'column',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  shortcutCard: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 15,
    marginBottom: 15,
    borderLeftWidth: 4,
    shadowColor: '#000000a9',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
    position: 'relative',
  },
  shortcutArrowContainer: {
    position: 'absolute',
    bottom: 20,
    right: 10,
    width: 40,
    height: 40,
    borderRadius: 50,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000000a9',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 2.65,
    elevation: 5,
    zIndex: 1,
  },
  shortcutIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  shortcutIconText: {
    fontSize: 24,
    color: '#fff',
    fontFamily: 'Poppins_600SemiBold',
  },
  shortcutHint: {
    fontSize: 12,
    color: '#636363ff',
    fontFamily: 'Poppins_500Medium',
    marginVertical: 5,
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: 'rgba(204, 204, 204, 0.91)',
    borderRadius: 20,
    alignSelf: 'flex-start',
  },
  shortcutTitle: {
    fontSize: 18,
    fontFamily: 'Poppins_700Bold',
    color: '#333',
    marginLeft: 5,
  },
  shortcutDescription: {
    fontSize: 14,
    color: '#666',
    fontFamily: 'Poppins_500Medium',
    marginLeft: 5,
  },
  logoutButton: {
    backgroundColor: '#007AFF',
    height: 50,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 100,
  },
  logoutButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  floatingButton: {
    position: 'absolute',
    right: 20,
    bottom: 100,
    width: 55,
    height: 55,
    borderRadius: 100,
    backgroundColor: '#FFC942',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000000a9',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  floatingButtonText: {
    fontSize: 28,
  },
  dateButton: {
    width: 60,
    height: 80,
    borderRadius: 10,
    backgroundColor: '#f0f0f0',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
  },
  activeDateButton: {
    backgroundColor: '#FFC942',
  },
  dateButtonText: {
    fontSize: 12,
    fontFamily: 'Poppins_700Bold',
    color: '#333',
  },
  eventCard: {
    backgroundColor: '#fff',
    borderRadius: 15,
    marginVertical: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  eventTitle: {
    fontSize: 16,
    fontFamily: 'Poppins_700Bold',
    color: '#333',
  },
  eventDate: {
    fontSize: 12,
    fontFamily: 'Poppins_500Medium',
    color: '#666',
    marginBottom: 15,
  },
  eventDescription: {
    fontSize: 14,
    fontFamily: 'Poppins_500Medium',
    color: '#444',
    lineHeight: 20,
  },
  sectionSelector: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 20,
    marginBottom: 20,
  },
});

export default styles;

