import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '90%',
    paddingBottom: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  modalTitle: {
    fontSize: 22,
    fontFamily: 'Poppins_700Bold',
    color: '#1a1a1a',
  },
  modalScrollView: {
    padding: 20,
  },
  formSubtitle: {
    fontSize: 14,
    fontFamily: 'Poppins_500Medium',
    color: '#666',
    textAlign: 'center',
    marginBottom: 20,
    width: '80%',
    alignSelf: 'center'
  },
  sacramentDisplayContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#e8f5e9',
    padding: 15,
    borderRadius: 10,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#4CAF50',
  },
  sacramentDisplayText: {
    fontSize: 18,
    fontFamily: 'Poppins_700Bold',
    color: '#2e7d32',
    marginLeft: 10,
  },
  noSacramentContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
    paddingHorizontal: 20,
  },
  noSacramentText: {
    fontSize: 16,
    fontFamily: 'Poppins_500Medium',
    color: '#666',
    textAlign: 'center',
    marginTop: 15,
  },

  // Input Styles
  inputWrapper: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 14,
    fontFamily: 'Poppins_600SemiBold',
    color: '#333',
    marginBottom: 8,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  textInput: {
    flex: 1,
    fontSize: 16,
    fontFamily: 'Poppins_400Regular',
    color: '#333',
  },
  inputText: {
    flex: 1,
    fontSize: 16,
    fontFamily: 'Poppins_400Regular',
    color: '#333',
  },
  placeholderText: {
    color: '#999',
  },
  inputHelperText: {
    fontSize: 12,
    fontFamily: 'Poppins_400Regular',
    color: '#666',
    marginTop: 5,
    marginLeft: 5,
  },

  // Info Container
  infoContainer: {
    backgroundColor: '#fff9e6',
    padding: 12,
    borderRadius: 8,
    marginBottom: 20,
    borderLeftWidth: 3,
    borderLeftColor: '#FFC942',
  },
  infoText: {
    fontSize: 13,
    fontFamily: 'Poppins_500Medium',
    color: '#666',
    marginBottom: 4,
  },

  // Upload Section
  uploadSection: {
    backgroundColor: '#f7f9fc',
    padding: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#dfe7f1',
    marginBottom: 20,
  },
  uploadSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  uploadBadge: {
    backgroundColor: '#e0f2f1',
    color: '#00796b',
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  uploadHelperText: {
    fontSize: 12,
    fontFamily: 'Poppins_400Regular',
    color: '#5f6c7b',
    marginBottom: 12,
  },
  uploadButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFC942',
    paddingVertical: 12,
    borderRadius: 10,
    justifyContent: 'center',
  },
  uploadButtonText: {
    fontSize: 15,
    fontFamily: 'Poppins_700Bold',
    color: '#424242',
  },

  // Upload Modal
  uploadModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  uploadModalContent: {
    backgroundColor: '#fff',
    borderRadius: 20,
    width: '100%',
    maxWidth: 420,
    maxHeight: '85%',
    padding: 20,
  },
  uploadModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  uploadModalSubtitle: {
    fontSize: 13,
    fontFamily: 'Poppins_500Medium',
    color: '#666',
    marginTop: 4,
  },
  uploadRequirementItem: {
    marginBottom: 16,
    padding: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    backgroundColor: '#fdfdfd',
  },
  uploadRequirementInfo: {
    marginBottom: 12,
  },
  uploadFileInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  uploadFileName: {
    marginLeft: 8,
    fontSize: 13,
    fontFamily: 'Poppins_500Medium',
    color: '#2e7d32',
    flex: 1,
  },
  uploadRequirementActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  uploadRequirementButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFE39B',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    flex: 1,
    marginRight: 10,
  },
  uploadRequirementButtonText: {
    fontSize: 13,
    fontFamily: 'Poppins_600SemiBold',
    color: '#424242',
  },
  uploadRequirementButtonSecondary: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#ffccd2',
    backgroundColor: '#fff5f5',
  },
  uploadRequirementButtonSecondaryText: {
    fontSize: 13,
    fontFamily: 'Poppins_600SemiBold',
    color: '#ff4444',
  },
  uploadEmptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  uploadModalCloseButton: {
    backgroundColor: '#FFC942',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 10,
  },

  // Error Styles
  errorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffebee',
    padding: 12,
    borderRadius: 8,
    marginBottom: 15,
    borderLeftWidth: 3,
    borderLeftColor: '#ff4444',
  },
  errorText: {
    flex: 1,
    fontSize: 13,
    fontFamily: 'Poppins_500Medium',
    color: '#ff4444',
    marginLeft: 8,
  },

  // Date Picker Modal
  datePickerModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  datePickerModalContent: {
    backgroundColor: '#fff',
    borderRadius: 20,
    width: '100%',
    maxWidth: 400,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  datePickerCloseButton: {
    backgroundColor: '#FFC942',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 20,
  },
  datePickerCloseButtonText: {
    fontSize: 16,
    fontFamily: 'Poppins_700Bold',
    color: '#424242',
  },

  // Submit Button
  submitButton: {
    backgroundColor: '#FFC942',
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 5,
    marginBottom: 40,
  },
  submitButtonText: {
    fontSize: 16,
    fontFamily: 'Poppins_700Bold',
    color: '#424242',
  },

  // QR Code Modal Styles
  qrCodeModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  qrCodeModalContent: {
    backgroundColor: '#fff',
    borderRadius: 20,
    width: '100%',
    maxWidth: 400,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  qrCodeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  qrCodeTitle: {
    fontSize: 22,
    fontFamily: 'Poppins_700Bold',
    color: '#1a1a1a',
  },
  qrCodeContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  qrCodeSubtitle: {
    fontSize: 14,
    fontFamily: 'Poppins_500Medium',
    color: '#666',
    textAlign: 'center',
    marginBottom: 15,
  },
  paymentAmountContainer: {
    backgroundColor: '#e8f5e9',
    padding: 15,
    borderRadius: 10,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#4CAF50',
    alignItems: 'center',
  },
  paymentAmountLabel: {
    fontSize: 13,
    fontFamily: 'Poppins_500Medium',
    color: '#666',
    marginBottom: 5,
  },
  paymentAmount: {
    fontSize: 24,
    fontFamily: 'Poppins_700Bold',
    color: '#2e7d32',
  },
  qrCodeImageWrapper: {
    backgroundColor: '#f5f5f5',
    padding: 20,
    borderRadius: 15,
    marginBottom: 20,
    borderWidth: 2,
    borderColor: '#e0e0e0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  qrCodeImage: {
    width: 250,
    height: 250,
  },
  bookingDetailsContainer: {
    width: '100%',
    backgroundColor: '#f9f9f9',
    padding: 15,
    borderRadius: 10,
    marginTop: 10,
  },
  bookingDetailsTitle: {
    fontSize: 16,
    fontFamily: 'Poppins_600SemiBold',
    color: '#333',
    marginBottom: 12,
  },
  bookingDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  bookingDetailText: {
    fontSize: 14,
    fontFamily: 'Poppins_400Regular',
    color: '#666',
    marginLeft: 10,
  },
  qrCodeCloseButton: {
    backgroundColor: '#FFC942',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 10,
  },
  qrCodeCloseButtonText: {
    fontSize: 16,
    fontFamily: 'Poppins_700Bold',
    color: '#424242',
  },
});

export default styles;

